server.port=8083
spring.application.name=settlement-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=settlement-group

management.endpoints.web.exposure.include=*
